//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> IsSubscribedToNewsletter { get; set; }
        public Nullable<int> MembershipTypeID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual MembershipType MembershipType { get; set; }
    }
}
