//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string Description { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> NumberInStock { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
